# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  redis-master:
    container_name: redis-master
    image: redis
    ports:
      - 6379:6379 


  redis-slave1:
    container_name: redis-slave1
    image: redis
    ports:
      - 6389:6379 
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 
    command: sh -c "redis-server /usr/local/etc/redis/redis.conf"
    external_links:
      - redis-master

  redis-slave2:
    container_name: redis.slave2
    image: redis
    ports:
      - 6399:6379 
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 
    command: sh -c "redis-server /usr/local/etc/redis/redis.conf"
    external_links:
      - redis-master
  redis-slave3:
    container_name: redis.slave3
    image: redis
    ports:
      - 6319:6379 
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 
    command: sh -c "redis-server /usr/local/etc/redis/redis.conf"
    external_links:
      - redis-master
